server:
  port: 6969
spring:
  application:
    name: mybatis_demo
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: ''
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mybatis_demo.entity

logging:
  level:
    com.example.ecommerce.mapper: DEBUG
    org.springframework.jdbc: DEBUG